services:
  backup:
    build: .
    container_name: backup
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_BACKUP_USER: ${MYSQL_BACKUP_USER}
      MYSQL_BACKUP_PASSWORD: ${MYSQL_BACKUP_PASSWORD}
      MYSQL_DATABASES_LIST: ${MYSQL_DATABASES_LIST}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      SYNC_SSH_KEY: ${SYNC_SSH_KEY}
      SYNC_USER: ${SYNC_BACKUP_USER}
      SYNC_HOST: ${SYNC_BACKUP_HOST}
      SYNC_REMOTE_DIR: ${SYNC_BACKUP_REMOTE_DIR}
      RETENTION_DAYS: ${RETENTION_DAYS}
      TZ: Europe/Ljubljana 
    volumes:
      - ${LOCAL_BACKUPS_DIR}:/backups
      - ${SYNC_SSH_KEY}:/root/.ssh/id_rsa:ro
    restart: unless-stopped
